const languages =[
  { id: 1, language: "abc", extension: ".abc" },
  { id: 2, language: "actionscript", extension: ".as" },
  { id: 3, language: "abap", extension: ".abap" },
  { id: 4, language: "ada", extension: ".ada" },
  { id: 5, language: "alda", extension: ".alda" },
  { id: 6, language: "apache_conf", extension: ".conf" },
  { id: 7, language: "apex", extension: ".cls" },
  { id: 8, language: "aql", extension: ".aql" },
  { id: 9, language: "asciidoc", extension: ".adoc" },
  { id: 10, language: "asl", extension: ".asl" },
  { id: 11, language: "assembly_arm32", extension: ".s" },
  { id: 12, language: "assembly_x86", extension: ".asm" },
  { id: 13, language: "astro", extension: ".astro" },
  { id: 14, language: "autohotkey", extension: ".ahk" },
  { id: 15, language: "batchfile", extension: ".bat" },
  { id: 16, language: "bibtex", extension: ".bib" },
  { id: 17, language: "c_cpp", extension: ".cpp" },
  { id: 18, language: "c9search", extension: ".c9search" },
  { id: 19, language: "cirru", extension: ".cirru" },
  { id: 20, language: "clojure", extension: ".clj" },
  { id: 21, language: "cobol", extension: ".cob" },
  { id: 22, language: "coffee", extension: ".coffee" },
  { id: 23, language: "coldfusion", extension: ".cfm" },
  { id: 24, language: "crystal", extension: ".cr" },
  { id: 25, language: "csharp", extension: ".cs" },
  { id: 26, language: "csound_document", extension: ".csd" },
  { id: 27, language: "csound_orchestra", extension: ".orc" },
  { id: 28, language: "csound_score", extension: ".sco" },
  { id: 29, language: "css", extension: ".css" },
  { id: 30, language: "curly", extension: ".curly" },
  { id: 31, language: "cuttlefish", extension: ".cuttlefish" },
  { id: 32, language: "d", extension: ".d" },
  { id: 33, language: "dart", extension: ".dart" },
  { id: 34, language: "diff", extension: ".diff" },
  { id: 35, language: "django", extension: ".django" },
  { id: 36, language: "dockerfile", extension: ".dockerfile" },
  { id: 37, language: "dot", extension: ".dot" },
  { id: 38, language: "drools", extension: ".drl" },
  { id: 39, language: "edifact", extension: ".edi" },
  { id: 40, language: "eiffel", extension: ".e" },
  { id: 41, language: "ejs", extension: ".ejs" },
  { id: 42, language: "elixir", extension: ".ex" },
  { id: 43, language: "elm", extension: ".elm" },
  { id: 44, language: "erlang", extension: ".erl" },
  { id: 45, language: "flix", extension: ".flix" },
  { id: 46, language: "forth", extension: ".forth" },
  { id: 47, language: "fortran", extension: ".f" },
  { id: 48, language: "fsharp", extension: ".fs" },
  { id: 49, language: "fsl", extension: ".fsl" },
  { id: 50, language: "ftl", extension: ".ftl" },
  { id: 51, language: "gcode", extension: ".gcode" },
  { id: 52, language: "gherkin", extension: ".feature" },
  { id: 53, language: "gitignore", extension: ".gitignore" },
  { id: 54, language: "glsl", extension: ".glsl" },
  { id: 55, language: "gobstones", extension: ".gbs" },
  { id: 56, language: "golang", extension: ".go" },
  { id: 57, language: "graphqlschema", extension: ".gql" },
  { id: 58, language: "groovy", extension: ".groovy" },
  { id: 59, language: "haml", extension: ".haml" },
  { id: 60, language: "handlebars", extension: ".hbs" },
  { id: 61, language: "haskell", extension: ".hs" },
  { id: 62, language: "haskell_cabal", extension: ".cabal" },
  { id: 63, language: "haxe", extension: ".hx" },
  { id: 64, language: "hjson", extension: ".hjson" },
  { id: 65, language: "html", extension: ".html" },
  { id: 66, language: "html_elixir", extension: ".eex" },
  { id: 67, language: "html_ruby", extension: ".erb" },
  { id: 68, language: "ini", extension: ".ini" },
  { id: 69, language: "io", extension: ".io" },
  { id: 70, language: "ion", extension: ".ion" },
  { id: 71, language: "jack", extension: ".jack" },
  { id: 72, language: "jade", extension: ".jade" },
  { id: 73, language: "java", extension: ".java" },
  { id: 74, language: "javascript", extension: ".js" },
  { id: 75, language: "jexl", extension: ".jexl" },
  { id: 76, language: "json", extension: ".json" },
  { id: 77, language: "json5", extension: ".json5" },
  { id: 78, language: "jsoniq", extension: ".jq" },
  { id: 79, language: "jsp", extension: ".jsp" },
  { id: 80, language: "jssm", extension: ".jssm" },
  { id: 81, language: "jsx", extension: ".jsx" },
  { id: 82, language: "julia", extension: ".jl" },
  { id: 83, language: "kotlin", extension: ".kt" },
  { id: 84, language: "latex", extension: ".tex" },
  { id: 85, language: "latte", extension: ".latte" },
  { id: 86, language: "less", extension: ".less" },
  { id: 87, language: "liquid", extension: ".liquid" },
  { id: 88, language: "lisp", extension: ".lisp" },
  { id: 89, language: "livescript", extension: ".ls" },
  { id: 90, language: "lisp", extension: ".lisp" },
  { id: 91, language: "logiql", extension: ".logic" },
  { id: 92, language: "logtalk", extension: ".lgt" },
  { id: 93, language: "lsl", extension: ".lsl" },
  { id: 94, language: "lua", extension: ".lua" },
  { id: 95, language: "luapage", extension: ".lp" },
  { id: 96, language: "lucene", extension: ".lucene" },
  { id: 97, language: "makefile", extension: ".mk" },
  { id: 98, language: "markdown", extension: ".md" },
  { id: 99, language: "mask", extension: ".mask" },
  { id: 100, language: "matlab", extension: ".mat" },
  { id: 101, language: "maze", extension: ".maze" },
  { id: 102, language: "mediawiki", extension: ".wiki" },
  { id: 103, language: "mel", extension: ".mel" },
  { id: 104, language: "mips", extension: ".mips" },
  { id: 105, language: "mixal", extension: ".mixal" },
  { id: 106, language: "mushcode", extension: ".mush" },
  { id: 107, language: "mysql", extension: ".sql" },
  { id: 108, language: "nasal", extension: ".nasl" },
  { id: 109, language: "nginx", extension: ".conf" },
  { id: 110, language: "nim", extension: ".nim" },
  { id: 111, language: "nix", extension: ".nix" },
  { id: 112, language: "nsis", extension: ".nsi" },
  { id: 113, language: "nunjucks", extension: ".njk" },
  { id: 114, language: "objectivec", extension: ".m" },
  { id: 115, language: "ocaml", extension: ".ml" },
  { id: 116, language: "odin", extension: ".odin" },
  { id: 117, language: "partiql", extension: ".sql" },
  { id: 118, language: "pascal", extension: ".pas" },
  { id: 119, language: "perl", extension: ".pl" },
  { id: 120, language: "pgsql", extension: ".sql" },
  { id: 121, language: "php", extension: ".php" },
  { id: 122, language: "php_laravel_blade", extension: ".blade.php" },
  { id: 123, language: "pig", extension: ".pig" },
  { id: 124, language: "plsql", extension: ".sql" },
  { id: 125, language: "powershell", extension: ".ps1" },
  { id: 126, language: "praat", extension: ".praat" },
  { id: 127, language: "prisma", extension: ".prisma" },
  { id: 128, language: "prolog", extension: ".pl" },
  { id: 129, language: "properties", extension: ".properties" },
  { id: 130, language: "protobuf", extension: ".proto" },
  { id: 131, language: "prql", extension: ".prql" },
  { id: 132, language: "puppet", extension: ".pp" },
  { id: 133, language: "python", extension: ".py" },
  { id: 134, language: "qml", extension: ".qml" },
  { id: 135, language: "r", extension: ".r" },
  { id: 136, language: "raku", extension: ".raku" },
  { id: 137, language: "razor", extension: ".cshtml" },
  { id: 138, language: "rdoc", extension: ".rdoc" },
  { id: 139, language: "red", extension: ".red" },
  { id: 140, language: "rhtml", extension: ".rhtml" },
  { id: 141, language: "robot", extension: ".robot" },
  { id: 142, language: "rst", extension: ".rst" },
  { id: 143, language: "ruby", extension: ".rb" },
  { id: 144, language: "rust", extension: ".rs" },
  { id: 145, language: "sac", extension: ".sac" },
  { id: 146, language: "sass", extension: ".sass" },
  { id: 147, language: "scad", extension: ".scad" },
  { id: 148, language: "scala", extension: ".scala" },
  { id: 149, language: "scheme", extension: ".scm" },
  { id: 150, language: "scrypt", extension: ".sc" },
  { id: 151, language: "scss", extension: ".scss" },
  { id: 152, language: "sh", extension: ".sh" },
  { id: 153, language: "sjs", extension: ".sjs" },
  { id: 154, language: "slim", extension: ".slim" },
  { id: 155, language: "smarty", extension: ".tpl" },
  { id: 156, language: "smithy", extension: ".sm" },
  { id: 157, language: "snippets", extension: ".snippets" },
  { id: 158, language: "soy_template", extension: ".soy" },
  { id: 159, language: "space", extension: ".space" },
  { id: 160, language: "sparql", extension: ".rq" },
  { id: 161, language: "sql", extension: ".sql" },
  { id: 162, language: "sqlserver", extension: ".sql" },
  { id: 163, language: "stylus", extension: ".styl" },
  { id: 164, language: "svg", extension: ".svg" },
  { id: 165, language: "swift", extension: ".swift" },
  { id: 166, language: "tcl", extension: ".tcl" },
  { id: 167, language: "terraform", extension: ".tf" },
  { id: 168, language: "tex", extension: ".tex" },
  { id: 169, language: "text", extension: ".txt" },
  { id: 170, language: "textile", extension: ".textile" },
  { id: 171, language: "toml", extension: ".toml" },
  { id: 172, language: "tsx", extension: ".tsx" },
  { id: 173, language: "turtle", extension: ".ttl" },
  { id: 174, language: "twig", extension: ".twig" },
  { id: 175, language: "typescript", extension: ".ts" },
  { id: 176, language: "vala", extension: ".vala" },
  { id: 177, language: "vbscript", extension: ".vbs" },
  { id: 178, language: "velocity", extension: ".vm" },
  { id: 179, language: "verilog", extension: ".v" },
  { id: 180, language: "vhdl", extension: ".vhd" },
  { id: 181, language: "visualforce", extension: ".vf" },
  { id: 182, language: "vue", extension: ".vue" },
  { id: 183, language: "wollok", extension: ".wlk" },
  { id: 184, language: "xml", extension: ".xml" },
  { id: 185, language: "xquery", extension: ".xq" },
  { id: 186, language: "yaml", extension: ".yaml" },
  { id: 187, language: "zeek", extension: ".zeek" },
  { id: 188, language: "zig", extension: ".zig" }
];
const themes = [
  { id: 1, theme: 'monokai', group: "dark" },
  { id: 2, theme: 'github', group: "bright" },
  { id: 3, theme: 'clouds', group: "bright" },
  { id: 4, theme: 'crimson_editor', group: "bright" },
  { id: 5, theme: 'dawn', group: "bright" },
  { id: 6, theme: 'dreamweaver', group: "bright" },
  { id: 7, theme: 'eclipse', group: "bright" },
  { id: 8, theme: 'iplastic', group: "bright" },
  { id: 9, theme: 'solarized_light', group: "bright" },
  { id: 10, theme: 'textmate', group: "bright" },
  { id: 11, theme: 'tomorrow', group: "bright" },
  { id: 12, theme: 'xcode', group: "bright" },
  { id: 13, theme: 'kuroir', group: "bright" },
  { id: 14, theme: 'katzenmilch', group: "bright" },
  { id: 15, theme: 'sqlserver', group: "bright" },
  { id: 16, theme: 'cloud_editor', group: "bright" },
  { id: 17, theme: 'ambiance', group: "dark" },
  { id: 18, theme: 'chaos', group: "dark" },
  { id: 19, theme: 'clouds_midnight', group: "dark" },
  { id: 20, theme: 'dracula', group: "dark" },
  { id: 21, theme: 'cobalt', group: "dark" },
  { id: 22, theme: 'gruvbox', group: "dark" },
  { id: 23, theme: 'gob', group: "dark" },
  { id: 24, theme: 'idle_fingers', group: "dark" },
  { id: 25, theme: 'kr_theme', group: "dark" },
  { id: 26, theme: 'merbivore', group: "dark" },
  { id: 27, theme: 'merbivore_soft', group: "dark" },
  { id: 28, theme: 'mono_industrial', group: "dark" },
  { id: 29, theme: 'nord_dark', group: "dark" },
  { id: 30, theme: 'one_dark', group: "dark" },
  { id: 31, theme: 'pastel_on_dark', group: "dark" },
  { id: 32, theme: 'solarized_dark', group: "dark" },
  { id: 33, theme: 'terminal', group: "dark" },
  { id: 34, theme: 'tomorrow_night', group: "dark" },
  { id: 35, theme: 'tomorrow_night_blue', group: "dark" },
  { id: 36, theme: 'tomorrow_night_bright', group: "dark" },
  { id: 37, theme: 'tomorrow_night_eighties', group: "dark" },
  { id: 38, theme: 'twilight', group: "dark" },
  { id: 39, theme: 'vibrant_ink', group: "dark" },
  { id: 40, theme: 'github_dark', group: "dark" },
  { id: 41, theme: 'cloud_editor_dark', group: "dark" }
];
;
  const fontSizes = [
    { id: 1, size: 12 },
    { id: 2, size: 14 },
    { id: 3, size: 16 },
    { id: 4, size: 18 },
    { id: 5, size: 20 },
    { id: 6, size: 22 },
    { id: 7, size: 24 },
    { id: 8, size: 26 },
    { id: 9, size: 28 },
    { id: 10, size: 30 },
    { id: 11, size: 32 },
    { id: 12, size: 34 },
    { id: 13, size: 36 },
    { id: 14, size: 38 },
    { id: 15, size: 40 },
    { id: 16, size: 42 },
    { id: 17, size: 44 },
    { id: 18, size: 46 },
    { id: 19, size: 48 },
    { id: 20, size: 50 }
  ];
//   console.log(languages);
export {
    languages,
    themes,
    fontSizes
}
  